# ! Change this to be your URL and Name ! 
baseurl      = "https://connectwith.davidpacold.dev"
title        = "David Pacold"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

# Google Analytics - ! Change this to be your ID or remove ! 
  googleAnalytics = 'G-GHBQN6V1R2'

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home ! Change this if you wish ! 
  homeSubtitle = "Where to find me"


  # Metadata mostly used in document's head ! Change this if you wish !
  description = "My Social Media Links"
  keywords = "homepage, blog, social"
  images = [""]

[author]
# ! Change this !
  name = "David Pacold"

 # Custom footer 
  # If you want, you can easily override the default footer with your own content. 
  #
  [params.footer]
#    trademark = true
#    rss = true
#    copyright = true
#    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"https://developers.cloudflare.com/pages/\">Cloudflare Pages</a>",
    ] 


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    # ! Change this if you wish !
    title = "Connect with me"
    subtitle = "My links"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

    [languages.en.params.logo]
    # ! Change this !
      logoText = "David Pacold"
      logoHomeLink = "/"

  # ! Change these !
  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://bsky.davidpacold.dev"

  [[params.social]]
    name = "email"
    url  = "mailto:dpacold@cloudflare.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/davidpacold"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/davidpacold"
